---
name: "Prunarr Bridge"
guid: "a8c0f8e4-7d3c-4b5a-9e2f-1a2b3c4d5e6f"
version: "2.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Bridge between Prunarr and Jellyfin for managing symlinks"
description: "Jellyfin plugin for Prunarr integration. Manages symlinks via HTTP API. v2.0+ uses simplified design: symlink management only, no library management."
category: "General"
owner: "prunarr"
changelog: |
  Version 2.0.0 - BREAKING CHANGES
  - Simplified to symlink-only design (Single Responsibility Principle)
  - Removed Virtual Folder management (Prunarr must handle this)
  - Removed library scanning (Prunarr must handle this)
  - Renamed endpoints: /leaving-soon/* → /symlinks/*
  - Removed /clear endpoint (use /remove for each item)
  - Added /symlinks/list endpoint
  - Removed AutoCreateVirtualFolder configuration
  - Removed VirtualFolderName configuration
  - See API.md for migration guide
artifacts:
  - "Jellyfin.Plugin.PrunarrBridge.dll"
build_type: "dotnet"
dotnet_configuration: "Release"
dotnet_framework: "net9.0"
